# Разрешаем локальные подключения (по умолчанию)
local   all             all                                     trust

# Разрешаем всем пользователям подключаться к любой базе с паролем (md5)
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5
