"""add cheking for uniqueness for chats

Revision ID: 443ec278cab1
Revises: bb608bf50977
Create Date: 2025-09-28 00:41:31.872251
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443ec278cab1'
down_revision = 'bb608bf50977'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chats_user1_user2', 'chats', ['user1_id', 'user2_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chats_user1_user2', 'chats', type_='unique')
    # ### end Alembic commands ###
