"""add default parametr for ids

Revision ID: bb608bf50977
Revises: ec60b85195b7
Create Date: 2025-09-27 17:37:32.012434
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb608bf50977'
down_revision = 'ec60b85195b7'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
