"""change ip column to INET

Revision ID: c9c521647d0e
Revises: 9f3f7e6a1c2b
Create Date: 2026-03-15 11:57:07.614529
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c521647d0e'
down_revision = '9f3f7e6a1c2b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_chats_user1_user2'), 'chats', type_='unique')
    op.drop_constraint(op.f('chats_user2_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_user1_id_fkey'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'user1_id')
    op.drop_column('chats', 'user2_id')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.add_column('chats', sa.Column('user2_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('user1_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chats_user1_id_fkey'), 'chats', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(op.f('chats_user2_id_fkey'), 'chats', 'users', ['user2_id'], ['id'])
    op.create_unique_constraint(op.f('uq_chats_user1_user2'), 'chats', ['user1_id', 'user2_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
