### CREATE CHAT

POST http://localhost:8000/chat/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNmJiNzRhOC1mY2QyLTQ3NTgtOTNjYS00ZDA1ZGYxOGE2OWIiLCJpYXQiOjE3NTkyOTI1ODQsIm5iZiI6MTc1OTI5MjU4NCwiZXhwIjoxNzU5MjkzNDg0LCJqdGkiOiJlOGI0YWRkOS1mYWI3LTQ1OWQtYjMyYi02NzA2MmVkNzdiOGUiLCJpc3MiOiJkZXBlbmRlZC1jaGF0IiwiYXVkIjoiZGVwZW5kZWQtdXNlcnMiLCJ0eXBlIjoiYWNjZXNzIiwiaWQiOiIxNmJiNzRhOC1mY2QyLTQ3NTgtOTNjYS00ZDA1ZGYxOGE2OWIiLCJ1c2VybmFtZSI6ImZlcmdzaW90In0.NglDyUBM728BEKziCSvSITPRcCwjIFoSt6C2s3xL1aU

{
  "user2_id": "4daaea25-b54c-47cf-a0c4-ac066010c3b0"
}

###